# 定义服务的一些公共配置

Services:
    # 服务名称
  - Name: DBService
    # 服务类型(用于服务发现时根据类型搜索服务)
    Type: db
    # 服务器ID(如果是游戏中使用,基本上必须定义)
    ServerId: 1
    # 定时器大小
    TimerSize: 100
    # 消息队列大小
    MailBoxSize: 1000
    # 协程数量
    GoroutineNum: 1
  - Name:  LoginService
    Type: login
    ServerId: 1
    TimerSize: 100
    MailBoxSize: 1000
    GoroutineNum: 1
