// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: internal/actor.proto

package actor

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GrpcListener_RPCCall_FullMethodName = "/actor.GrpcListener/RPCCall"
)

// GrpcListenerClient is the client API for GrpcListener service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GrpcListenerClient interface {
	RPCCall(ctx context.Context, in *Message, opts ...grpc.CallOption) (*RpcCallResponse, error)
}

type grpcListenerClient struct {
	cc grpc.ClientConnInterface
}

func NewGrpcListenerClient(cc grpc.ClientConnInterface) GrpcListenerClient {
	return &grpcListenerClient{cc}
}

func (c *grpcListenerClient) RPCCall(ctx context.Context, in *Message, opts ...grpc.CallOption) (*RpcCallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RpcCallResponse)
	err := c.cc.Invoke(ctx, GrpcListener_RPCCall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrpcListenerServer is the server API for GrpcListener service.
// All implementations must embed UnimplementedGrpcListenerServer
// for forward compatibility.
type GrpcListenerServer interface {
	RPCCall(context.Context, *Message) (*RpcCallResponse, error)
	mustEmbedUnimplementedGrpcListenerServer()
}

// UnimplementedGrpcListenerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGrpcListenerServer struct{}

func (UnimplementedGrpcListenerServer) RPCCall(context.Context, *Message) (*RpcCallResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RPCCall not implemented")
}
func (UnimplementedGrpcListenerServer) mustEmbedUnimplementedGrpcListenerServer() {}
func (UnimplementedGrpcListenerServer) testEmbeddedByValue()                      {}

// UnsafeGrpcListenerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GrpcListenerServer will
// result in compilation errors.
type UnsafeGrpcListenerServer interface {
	mustEmbedUnimplementedGrpcListenerServer()
}

func RegisterGrpcListenerServer(s grpc.ServiceRegistrar, srv GrpcListenerServer) {
	// If the following call pancis, it indicates UnimplementedGrpcListenerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GrpcListener_ServiceDesc, srv)
}

func _GrpcListener_RPCCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcListenerServer).RPCCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrpcListener_RPCCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcListenerServer).RPCCall(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

// GrpcListener_ServiceDesc is the grpc.ServiceDesc for GrpcListener service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GrpcListener_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "actor.GrpcListener",
	HandlerType: (*GrpcListenerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RPCCall",
			Handler:    _GrpcListener_RPCCall_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/actor.proto",
}
