// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.23.3
// source: msg.proto

package msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Msg_Test_Req struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             int32                  `protobuf:"varint,1,opt,name=A,proto3" json:"A,omitempty"`
	B             int32                  `protobuf:"varint,2,opt,name=B,proto3" json:"B,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Msg_Test_Req) Reset() {
	*x = Msg_Test_Req{}
	mi := &file_msg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Msg_Test_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Msg_Test_Req) ProtoMessage() {}

func (x *Msg_Test_Req) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Msg_Test_Req.ProtoReflect.Descriptor instead.
func (*Msg_Test_Req) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{0}
}

func (x *Msg_Test_Req) GetA() int32 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *Msg_Test_Req) GetB() int32 {
	if x != nil {
		return x.B
	}
	return 0
}

type Msg_Test_Resp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ret           int32                  `protobuf:"varint,1,opt,name=Ret,proto3" json:"Ret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Msg_Test_Resp) Reset() {
	*x = Msg_Test_Resp{}
	mi := &file_msg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Msg_Test_Resp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Msg_Test_Resp) ProtoMessage() {}

func (x *Msg_Test_Resp) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Msg_Test_Resp.ProtoReflect.Descriptor instead.
func (*Msg_Test_Resp) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{1}
}

func (x *Msg_Test_Resp) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

type TestData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             int32                  `protobuf:"varint,1,opt,name=A,proto3" json:"A,omitempty"`
	B             int32                  `protobuf:"varint,2,opt,name=B,proto3" json:"B,omitempty"`
	Version       int64                  `protobuf:"varint,3,opt,name=Version,proto3" json:"Version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestData) Reset() {
	*x = TestData{}
	mi := &file_msg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestData) ProtoMessage() {}

func (x *TestData) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestData.ProtoReflect.Descriptor instead.
func (*TestData) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{2}
}

func (x *TestData) GetA() int32 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *TestData) GetB() int32 {
	if x != nil {
		return x.B
	}
	return 0
}

func (x *TestData) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type TestGetAllDataResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *TestData              `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestGetAllDataResp) Reset() {
	*x = TestGetAllDataResp{}
	mi := &file_msg_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestGetAllDataResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestGetAllDataResp) ProtoMessage() {}

func (x *TestGetAllDataResp) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestGetAllDataResp.ProtoReflect.Descriptor instead.
func (*TestGetAllDataResp) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{3}
}

func (x *TestGetAllDataResp) GetData() *TestData {
	if x != nil {
		return x.Data
	}
	return nil
}

type TestLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Opt           int32                  `protobuf:"varint,1,opt,name=Opt,proto3" json:"Opt,omitempty"`
	Param         int32                  `protobuf:"varint,2,opt,name=Param,proto3" json:"Param,omitempty"`
	Version       int64                  `protobuf:"varint,3,opt,name=Version,proto3" json:"Version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestLog) Reset() {
	*x = TestLog{}
	mi := &file_msg_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestLog) ProtoMessage() {}

func (x *TestLog) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestLog.ProtoReflect.Descriptor instead.
func (*TestLog) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{4}
}

func (x *TestLog) GetOpt() int32 {
	if x != nil {
		return x.Opt
	}
	return 0
}

func (x *TestLog) GetParam() int32 {
	if x != nil {
		return x.Param
	}
	return 0
}

func (x *TestLog) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type EmptyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyReq) Reset() {
	*x = EmptyReq{}
	mi := &file_msg_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyReq) ProtoMessage() {}

func (x *EmptyReq) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyReq.ProtoReflect.Descriptor instead.
func (*EmptyReq) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{5}
}

type EmptyResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyResp) Reset() {
	*x = EmptyResp{}
	mi := &file_msg_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyResp) ProtoMessage() {}

func (x *EmptyResp) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyResp.ProtoReflect.Descriptor instead.
func (*EmptyResp) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{6}
}

var File_msg_proto protoreflect.FileDescriptor

const file_msg_proto_rawDesc = "" +
	"\n" +
	"\tmsg.proto\x12\tlogin_msg\"*\n" +
	"\fMsg_Test_Req\x12\f\n" +
	"\x01A\x18\x01 \x01(\x05R\x01A\x12\f\n" +
	"\x01B\x18\x02 \x01(\x05R\x01B\"!\n" +
	"\rMsg_Test_Resp\x12\x10\n" +
	"\x03Ret\x18\x01 \x01(\x05R\x03Ret\"@\n" +
	"\bTestData\x12\f\n" +
	"\x01A\x18\x01 \x01(\x05R\x01A\x12\f\n" +
	"\x01B\x18\x02 \x01(\x05R\x01B\x12\x18\n" +
	"\aVersion\x18\x03 \x01(\x03R\aVersion\"=\n" +
	"\x12TestGetAllDataResp\x12'\n" +
	"\x04data\x18\x01 \x01(\v2\x13.login_msg.TestDataR\x04data\"K\n" +
	"\aTestLog\x12\x10\n" +
	"\x03Opt\x18\x01 \x01(\x05R\x03Opt\x12\x14\n" +
	"\x05Param\x18\x02 \x01(\x05R\x05Param\x12\x18\n" +
	"\aVersion\x18\x03 \x01(\x03R\aVersion\"\n" +
	"\n" +
	"\bEmptyReq\"\v\n" +
	"\tEmptyResp2C\n" +
	"\vTestService\x124\n" +
	"\aTestFun\x12\x13.login_msg.EmptyReq\x1a\x14.login_msg.EmptyRespB\aZ\x05.;msgb\x06proto3"

var (
	file_msg_proto_rawDescOnce sync.Once
	file_msg_proto_rawDescData []byte
)

func file_msg_proto_rawDescGZIP() []byte {
	file_msg_proto_rawDescOnce.Do(func() {
		file_msg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_msg_proto_rawDesc), len(file_msg_proto_rawDesc)))
	})
	return file_msg_proto_rawDescData
}

var file_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_msg_proto_goTypes = []any{
	(*Msg_Test_Req)(nil),       // 0: login_msg.Msg_Test_Req
	(*Msg_Test_Resp)(nil),      // 1: login_msg.Msg_Test_Resp
	(*TestData)(nil),           // 2: login_msg.TestData
	(*TestGetAllDataResp)(nil), // 3: login_msg.TestGetAllDataResp
	(*TestLog)(nil),            // 4: login_msg.TestLog
	(*EmptyReq)(nil),           // 5: login_msg.EmptyReq
	(*EmptyResp)(nil),          // 6: login_msg.EmptyResp
}
var file_msg_proto_depIdxs = []int32{
	2, // 0: login_msg.TestGetAllDataResp.data:type_name -> login_msg.TestData
	5, // 1: login_msg.TestService.TestFun:input_type -> login_msg.EmptyReq
	6, // 2: login_msg.TestService.TestFun:output_type -> login_msg.EmptyResp
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_msg_proto_init() }
func file_msg_proto_init() {
	if File_msg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_msg_proto_rawDesc), len(file_msg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_msg_proto_goTypes,
		DependencyIndexes: file_msg_proto_depIdxs,
		MessageInfos:      file_msg_proto_msgTypes,
	}.Build()
	File_msg_proto = out.File
	file_msg_proto_goTypes = nil
	file_msg_proto_depIdxs = nil
}
