// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.23.3
// source: actor.proto

package actor

import (
	any1 "github.com/golang/protobuf/ptypes/any"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`         // 服务地址
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`               // 服务名称
	ServiceType   string                 `protobuf:"bytes,3,opt,name=ServiceType,proto3" json:"ServiceType,omitempty"` // 服务类型
	ServiceId     string                 `protobuf:"bytes,4,opt,name=ServiceId,proto3" json:"ServiceId,omitempty"`     // 同类型服务内唯一标识
	State         int32                  `protobuf:"varint,5,opt,name=State,proto3" json:"State,omitempty"`            // 服务状态(0: 正常, 1: 退休)
	Partition     int32                  `protobuf:"varint,6,opt,name=Partition,proto3" json:"Partition,omitempty"`    // 服务分区ID(用于服务路由隔离)
	Version       int64                  `protobuf:"varint,7,opt,name=Version,proto3" json:"Version,omitempty"`        // 服务版本号
	RpcType       string                 `protobuf:"bytes,8,opt,name=RpcType,proto3" json:"RpcType,omitempty"`         // rpc类型(默认使用nats)
	NodeUid       string                 `protobuf:"bytes,9,opt,name=NodeUid,proto3" json:"NodeUid,omitempty"`         // 节点唯一标识(这个主要是用来区分本地服务用的)
	IsMaster      bool                   `protobuf:"varint,10,opt,name=IsMaster,proto3" json:"IsMaster,omitempty"`     // 是否是主服务(主从)
	ServiceUid    string                 `protobuf:"bytes,11,opt,name=ServiceUid,proto3" json:"ServiceUid,omitempty"`  // 服务实例唯一id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PID) Reset() {
	*x = PID{}
	mi := &file_actor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PID) ProtoMessage() {}

func (x *PID) ProtoReflect() protoreflect.Message {
	mi := &file_actor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PID.ProtoReflect.Descriptor instead.
func (*PID) Descriptor() ([]byte, []int) {
	return file_actor_proto_rawDescGZIP(), []int{0}
}

func (x *PID) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PID) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PID) GetServiceType() string {
	if x != nil {
		return x.ServiceType
	}
	return ""
}

func (x *PID) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *PID) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *PID) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *PID) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PID) GetRpcType() string {
	if x != nil {
		return x.RpcType
	}
	return ""
}

func (x *PID) GetNodeUid() string {
	if x != nil {
		return x.NodeUid
	}
	return ""
}

func (x *PID) GetIsMaster() bool {
	if x != nil {
		return x.IsMaster
	}
	return false
}

func (x *PID) GetServiceUid() string {
	if x != nil {
		return x.ServiceUid
	}
	return ""
}

type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// === 路由信息 ===
	SenderPid   *PID `protobuf:"bytes,1,opt,name=SenderPid,proto3" json:"SenderPid,omitempty"`     // 发送者
	ReceiverPid *PID `protobuf:"bytes,2,opt,name=ReceiverPid,proto3" json:"ReceiverPid,omitempty"` // 接收者
	// === 调度属性（显式字段） ===
	Priority      int32  `protobuf:"varint,3,opt,name=Priority,proto3" json:"Priority,omitempty"`          // 优先级
	DispatcherKey string `protobuf:"bytes,4,opt,name=DispatcherKey,proto3" json:"DispatcherKey,omitempty"` // 分发键（用于分区/顺序保证）
	// === RPC 信息 ===
	Method       string    `protobuf:"bytes,5,opt,name=Method,proto3" json:"Method,omitempty"`               // 调用方法
	Request      *any1.Any `protobuf:"bytes,6,opt,name=Request,proto3" json:"Request,omitempty"`             // 方法参数
	Response     *any1.Any `protobuf:"bytes,7,opt,name=Response,proto3" json:"Response,omitempty"`           // 方法返回值
	Err          string    `protobuf:"bytes,8,opt,name=Err,proto3" json:"Err,omitempty"`                     // 错误信息
	Reply        bool      `protobuf:"varint,9,opt,name=Reply,proto3" json:"Reply,omitempty"`                // 是否是回复
	ReqId        uint64    `protobuf:"varint,10,opt,name=ReqId,proto3" json:"ReqId,omitempty"`               // 请求ID
	NeedResp     bool      `protobuf:"varint,11,opt,name=NeedResp,proto3" json:"NeedResp,omitempty"`         // 是否需要回复
	CompressType int32     `protobuf:"varint,12,opt,name=CompressType,proto3" json:"CompressType,omitempty"` // 压缩类型(0无压缩)
	// === 上下文元数据（仅用于 tracing/metadata） ===
	ContextHeaders map[string]string `protobuf:"bytes,13,rep,name=ContextHeaders,proto3" json:"ContextHeaders,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 上下文头（traceId 等）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_actor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_actor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_actor_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetSenderPid() *PID {
	if x != nil {
		return x.SenderPid
	}
	return nil
}

func (x *Message) GetReceiverPid() *PID {
	if x != nil {
		return x.ReceiverPid
	}
	return nil
}

func (x *Message) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Message) GetDispatcherKey() string {
	if x != nil {
		return x.DispatcherKey
	}
	return ""
}

func (x *Message) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Message) GetRequest() *any1.Any {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *Message) GetResponse() *any1.Any {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *Message) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

func (x *Message) GetReply() bool {
	if x != nil {
		return x.Reply
	}
	return false
}

func (x *Message) GetReqId() uint64 {
	if x != nil {
		return x.ReqId
	}
	return 0
}

func (x *Message) GetNeedResp() bool {
	if x != nil {
		return x.NeedResp
	}
	return false
}

func (x *Message) GetCompressType() int32 {
	if x != nil {
		return x.CompressType
	}
	return 0
}

func (x *Message) GetContextHeaders() map[string]string {
	if x != nil {
		return x.ContextHeaders
	}
	return nil
}

type RpcCallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcCallResponse) Reset() {
	*x = RpcCallResponse{}
	mi := &file_actor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcCallResponse) ProtoMessage() {}

func (x *RpcCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_actor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcCallResponse.ProtoReflect.Descriptor instead.
func (*RpcCallResponse) Descriptor() ([]byte, []int) {
	return file_actor_proto_rawDescGZIP(), []int{2}
}

type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// === 事件标识 ===
	Type int32 `protobuf:"varint,1,opt,name=Type,proto3" json:"Type,omitempty"` // 事件类型
	// === 调度属性（显式字段） ===
	Priority      int32  `protobuf:"varint,2,opt,name=Priority,proto3" json:"Priority,omitempty"`          // 优先级
	DispatcherKey string `protobuf:"bytes,3,opt,name=DispatcherKey,proto3" json:"DispatcherKey,omitempty"` // 分发键（用于分区/顺序保证）
	Deadline      int64  `protobuf:"varint,4,opt,name=Deadline,proto3" json:"Deadline,omitempty"`          // 事件处理截止时间(单位: 纳秒)
	// === 路由信息 ===
	Partition  int32  `protobuf:"varint,5,opt,name=Partition,proto3" json:"Partition,omitempty"`  // 目标分区ID
	ServiceUid string `protobuf:"bytes,6,opt,name=ServiceUid,proto3" json:"ServiceUid,omitempty"` // 目标服务实例唯一id
	// === 数据 ===
	Payload *any1.Any `protobuf:"bytes,7,opt,name=Payload,proto3" json:"Payload,omitempty"` // 实际事件数据
	// === 上下文元数据（仅用于 tracing/metadata） ===
	ContextHeaders map[string]string `protobuf:"bytes,8,rep,name=ContextHeaders,proto3" json:"ContextHeaders,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 上下文头（traceId 等）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_actor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_actor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_actor_proto_rawDescGZIP(), []int{3}
}

func (x *Event) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Event) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Event) GetDispatcherKey() string {
	if x != nil {
		return x.DispatcherKey
	}
	return ""
}

func (x *Event) GetDeadline() int64 {
	if x != nil {
		return x.Deadline
	}
	return 0
}

func (x *Event) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *Event) GetServiceUid() string {
	if x != nil {
		return x.ServiceUid
	}
	return ""
}

func (x *Event) GetPayload() *any1.Any {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetContextHeaders() map[string]string {
	if x != nil {
		return x.ContextHeaders
	}
	return nil
}

type MasterStateData struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OldStateIsMaster bool                   `protobuf:"varint,1,opt,name=OldStateIsMaster,proto3" json:"OldStateIsMaster,omitempty"`
	PrevEpoch        int64                  `protobuf:"varint,2,opt,name=PrevEpoch,proto3" json:"PrevEpoch,omitempty"`
	NewEpoch         int64                  `protobuf:"varint,3,opt,name=NewEpoch,proto3" json:"NewEpoch,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MasterStateData) Reset() {
	*x = MasterStateData{}
	mi := &file_actor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MasterStateData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MasterStateData) ProtoMessage() {}

func (x *MasterStateData) ProtoReflect() protoreflect.Message {
	mi := &file_actor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MasterStateData.ProtoReflect.Descriptor instead.
func (*MasterStateData) Descriptor() ([]byte, []int) {
	return file_actor_proto_rawDescGZIP(), []int{4}
}

func (x *MasterStateData) GetOldStateIsMaster() bool {
	if x != nil {
		return x.OldStateIsMaster
	}
	return false
}

func (x *MasterStateData) GetPrevEpoch() int64 {
	if x != nil {
		return x.PrevEpoch
	}
	return 0
}

func (x *MasterStateData) GetNewEpoch() int64 {
	if x != nil {
		return x.NewEpoch
	}
	return 0
}

var File_actor_proto protoreflect.FileDescriptor

const file_actor_proto_rawDesc = "" +
	"\n" +
	"\vactor.proto\x12\x05actor\x1a\x19google/protobuf/any.proto\"\xb1\x02\n" +
	"\x03PID\x12\x18\n" +
	"\aAddress\x18\x01 \x01(\tR\aAddress\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12 \n" +
	"\vServiceType\x18\x03 \x01(\tR\vServiceType\x12\x1c\n" +
	"\tServiceId\x18\x04 \x01(\tR\tServiceId\x12\x14\n" +
	"\x05State\x18\x05 \x01(\x05R\x05State\x12\x1c\n" +
	"\tPartition\x18\x06 \x01(\x05R\tPartition\x12\x18\n" +
	"\aVersion\x18\a \x01(\x03R\aVersion\x12\x18\n" +
	"\aRpcType\x18\b \x01(\tR\aRpcType\x12\x18\n" +
	"\aNodeUid\x18\t \x01(\tR\aNodeUid\x12\x1a\n" +
	"\bIsMaster\x18\n" +
	" \x01(\bR\bIsMaster\x12\x1e\n" +
	"\n" +
	"ServiceUid\x18\v \x01(\tR\n" +
	"ServiceUid\"\xaa\x04\n" +
	"\aMessage\x12(\n" +
	"\tSenderPid\x18\x01 \x01(\v2\n" +
	".actor.PIDR\tSenderPid\x12,\n" +
	"\vReceiverPid\x18\x02 \x01(\v2\n" +
	".actor.PIDR\vReceiverPid\x12\x1a\n" +
	"\bPriority\x18\x03 \x01(\x05R\bPriority\x12$\n" +
	"\rDispatcherKey\x18\x04 \x01(\tR\rDispatcherKey\x12\x16\n" +
	"\x06Method\x18\x05 \x01(\tR\x06Method\x12.\n" +
	"\aRequest\x18\x06 \x01(\v2\x14.google.protobuf.AnyR\aRequest\x120\n" +
	"\bResponse\x18\a \x01(\v2\x14.google.protobuf.AnyR\bResponse\x12\x10\n" +
	"\x03Err\x18\b \x01(\tR\x03Err\x12\x14\n" +
	"\x05Reply\x18\t \x01(\bR\x05Reply\x12\x14\n" +
	"\x05ReqId\x18\n" +
	" \x01(\x04R\x05ReqId\x12\x1a\n" +
	"\bNeedResp\x18\v \x01(\bR\bNeedResp\x12\"\n" +
	"\fCompressType\x18\f \x01(\x05R\fCompressType\x12J\n" +
	"\x0eContextHeaders\x18\r \x03(\v2\".actor.Message.ContextHeadersEntryR\x0eContextHeaders\x1aA\n" +
	"\x13ContextHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x11\n" +
	"\x0fRpcCallResponse\"\xf4\x02\n" +
	"\x05Event\x12\x12\n" +
	"\x04Type\x18\x01 \x01(\x05R\x04Type\x12\x1a\n" +
	"\bPriority\x18\x02 \x01(\x05R\bPriority\x12$\n" +
	"\rDispatcherKey\x18\x03 \x01(\tR\rDispatcherKey\x12\x1a\n" +
	"\bDeadline\x18\x04 \x01(\x03R\bDeadline\x12\x1c\n" +
	"\tPartition\x18\x05 \x01(\x05R\tPartition\x12\x1e\n" +
	"\n" +
	"ServiceUid\x18\x06 \x01(\tR\n" +
	"ServiceUid\x12.\n" +
	"\aPayload\x18\a \x01(\v2\x14.google.protobuf.AnyR\aPayload\x12H\n" +
	"\x0eContextHeaders\x18\b \x03(\v2 .actor.Event.ContextHeadersEntryR\x0eContextHeaders\x1aA\n" +
	"\x13ContextHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"w\n" +
	"\x0fMasterStateData\x12*\n" +
	"\x10OldStateIsMaster\x18\x01 \x01(\bR\x10OldStateIsMaster\x12\x1c\n" +
	"\tPrevEpoch\x18\x02 \x01(\x03R\tPrevEpoch\x12\x1a\n" +
	"\bNewEpoch\x18\x03 \x01(\x03R\bNewEpoch2A\n" +
	"\fGrpcListener\x121\n" +
	"\aRPCCall\x12\x0e.actor.Message\x1a\x16.actor.RpcCallResponseB\tZ\a.;actorb\x06proto3"

var (
	file_actor_proto_rawDescOnce sync.Once
	file_actor_proto_rawDescData []byte
)

func file_actor_proto_rawDescGZIP() []byte {
	file_actor_proto_rawDescOnce.Do(func() {
		file_actor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_actor_proto_rawDesc), len(file_actor_proto_rawDesc)))
	})
	return file_actor_proto_rawDescData
}

var file_actor_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_actor_proto_goTypes = []any{
	(*PID)(nil),             // 0: actor.PID
	(*Message)(nil),         // 1: actor.Message
	(*RpcCallResponse)(nil), // 2: actor.RpcCallResponse
	(*Event)(nil),           // 3: actor.Event
	(*MasterStateData)(nil), // 4: actor.MasterStateData
	nil,                     // 5: actor.Message.ContextHeadersEntry
	nil,                     // 6: actor.Event.ContextHeadersEntry
	(*any1.Any)(nil),        // 7: google.protobuf.Any
}
var file_actor_proto_depIdxs = []int32{
	0, // 0: actor.Message.SenderPid:type_name -> actor.PID
	0, // 1: actor.Message.ReceiverPid:type_name -> actor.PID
	7, // 2: actor.Message.Request:type_name -> google.protobuf.Any
	7, // 3: actor.Message.Response:type_name -> google.protobuf.Any
	5, // 4: actor.Message.ContextHeaders:type_name -> actor.Message.ContextHeadersEntry
	7, // 5: actor.Event.Payload:type_name -> google.protobuf.Any
	6, // 6: actor.Event.ContextHeaders:type_name -> actor.Event.ContextHeadersEntry
	1, // 7: actor.GrpcListener.RPCCall:input_type -> actor.Message
	2, // 8: actor.GrpcListener.RPCCall:output_type -> actor.RpcCallResponse
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_actor_proto_init() }
func file_actor_proto_init() {
	if File_actor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_actor_proto_rawDesc), len(file_actor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_actor_proto_goTypes,
		DependencyIndexes: file_actor_proto_depIdxs,
		MessageInfos:      file_actor_proto_msgTypes,
	}.Build()
	File_actor_proto = out.File
	file_actor_proto_goTypes = nil
	file_actor_proto_depIdxs = nil
}
