package xcontext

import (
	"context"
	"testing"

	"github.com/njtc406/emberengine/engine/pkg/def"
	"github.com/njtc406/emberengine/engine/pkg/utils/emberctx"
)

// --- P2-5: TraceID 贯通验证 ---

func TestNewWithCloneCtx_PreservesTraceID(t *testing.T) {
	// 构造带 traceId 的原始 context
	origCtx := emberctx.AddHeader(context.Background(), def.DefaultTraceIdKey, "trace-abc-123")

	cloned := NewWithCloneCtx(origCtx)

	got := cloned.GetTranceId()
	if got != "trace-abc-123" {
		t.Errorf("traceId after clone = %q, want %q", got, "trace-abc-123")
	}
}

func TestNewWithCloneCtx_PreservesCustomHeaders(t *testing.T) {
	origCtx := emberctx.AddHeader(context.Background(), def.DefaultTraceIdKey, "trace-xyz")
	origCtx = emberctx.AddHeader(origCtx, "custom-key", "custom-val")

	cloned := NewWithCloneCtx(origCtx)

	if got := cloned.GetTranceId(); got != "trace-xyz" {
		t.Errorf("traceId = %q, want %q", got, "trace-xyz")
	}
	if got := cloned.GetHeader("custom-key"); got != "custom-val" {
		t.Errorf("custom-key = %v, want %q", got, "custom-val")
	}
}

func TestNewWithCloneCtx_CancelDoesNotPropagate(t *testing.T) {
	parentCtx, cancel := context.WithCancel(context.Background())
	parentCtx = emberctx.AddHeader(parentCtx, def.DefaultTraceIdKey, "trace-cancel-test")

	cloned := NewWithCloneCtx(parentCtx)

	// 取消父 context
	cancel()

	// 克隆后的 context 不受影响
	if err := cloned.Context.Err(); err != nil {
		t.Errorf("cloned ctx should not be cancelled, got err: %v", err)
	}
	// traceId 仍然存在
	if got := cloned.GetTranceId(); got != "trace-cancel-test" {
		t.Errorf("traceId after cancel = %q, want %q", got, "trace-cancel-test")
	}
}

func TestNewWithCloneCtx_NilCtx_GeneratesTraceID(t *testing.T) {
	cloned := NewWithCloneCtx(nil)
	// NewCtx (called inside) should generate a traceId
	got := cloned.GetTranceId()
	if got == "" {
		t.Error("traceId should be auto-generated for nil ctx")
	}
}

func TestNewWithTimeout_PreservesTraceID(t *testing.T) {
	origCtx := emberctx.AddHeader(context.Background(), def.DefaultTraceIdKey, "trace-timeout-test")

	xctx, cancel := NewWithTimeout(origCtx, 5e9) // 5s
	defer cancel()

	if got := xctx.GetTranceId(); got != "trace-timeout-test" {
		t.Errorf("traceId after timeout wrap = %q, want %q", got, "trace-timeout-test")
	}
}

func TestNew_AutoGeneratesTraceID(t *testing.T) {
	// emberctx.NewCtx 会自动生成 traceId
	ctx := emberctx.NewCtx(nil)
	xctx := New(ctx)

	got := xctx.GetTranceId()
	if got == "" {
		t.Error("traceId should be auto-generated by NewCtx")
	}
}

func TestToHeaders_PreservesTraceID(t *testing.T) {
	ctx := emberctx.AddHeader(context.Background(), def.DefaultTraceIdKey, "trace-to-headers")
	xctx := New(ctx)

	headers := xctx.ToHeaders()
	if headers[def.DefaultTraceIdKey] != "trace-to-headers" {
		t.Errorf("ToHeaders traceId = %q, want %q", headers[def.DefaultTraceIdKey], "trace-to-headers")
	}
}

func TestSetHeadersWithMap_RestoresTraceID(t *testing.T) {
	// 模拟远程端反序列化后重建 context
	wireHeaders := map[string]string{
		def.DefaultTraceIdKey: "trace-wire-roundtrip",
		"custom":              "value",
	}

	xctx := New(context.Background())
	xctx.SetHeadersWithMap(wireHeaders)

	if got := xctx.GetTranceId(); got != "trace-wire-roundtrip" {
		t.Errorf("restored traceId = %q, want %q", got, "trace-wire-roundtrip")
	}
	if got := xctx.GetHeader("custom"); got != "value" {
		t.Errorf("restored custom = %v, want %q", got, "value")
	}
}

func TestContextFactory_NewContext_GeneratesUniqueTraceIDs(t *testing.T) {
	factory := NewFactory(map[string]any{
		def.DefaultDispatcherKey: "worker-test",
	})

	ids := make(map[string]bool, 100)
	for i := 0; i < 100; i++ {
		ctx := factory.NewContext()
		id := ctx.GetTranceId()
		if id == "" {
			t.Fatalf("factory.NewContext() produced empty traceId at iteration %d", i)
		}
		if ids[id] {
			t.Fatalf("duplicate traceId at iteration %d: %s", i, id)
		}
		ids[id] = true
	}
}
