## 系统基础配置

NodeConf:
  NodeId: 1
  # 系统状态(debug/release)
  SystemStatus: debug
  # 系统数据目录(持久化)
  PVCPath: ./example/data
  # 系统缓存目录
  PVPath: ./example/cache
  # 性能监控(0表示不开启监控)
  ProfilerInterval: 10s
  # 线程池大小
  AntsPoolSize: 100000
  # 定时器数量(用于监控rpc调用的timer)
  MonitorTimerSize: 10000
  # 定时器桶数量(决定锁的粒度)
  MonitorBucketSize: 20

ClusterConf:
  ETCDConf:
    # etcd地址
    EndPoints:
      - ${REMOTE_HOST}:2379
    DialTimeout: 3s
    # etcd用户名
    UserName: root
    # etcd密码
    Password: 123456
    # 是否开启日志
    NoLogger: true
  RPCServers:
      # 监听地址
    - Addr: 0.0.0.0:6680
      # 协议
      Protoc: "tcp"
      # rpc类型
      Type: "rpcx"
    - Addr: 0.0.0.0:6681
      Protoc: "tcp"
      Type: "grpc"
    - Addr: nats://${REMOTE_HOST}:4222
      Protoc: "tcp"
      Type: "nats"
  DiscoveryType: etcd
  RemoteConfPath: ""
  DiscoveryConf:
    Path: /server/rpc

ServiceConf:
  OpenRemote: false
  RemoteConfPath: ""
  StartServices:
    # 服务名称
    - ClassName: ConcurrencyTest1
      ServiceName: ConcurrencyTest1
      Type: test
      ServerId: 1
      RpcType: "nats"
      TimerConf:
        # 定时器队列长度
        TimerSize: 1000
        # 定时器桶大小
        TimerBucketSize: 100
      WorkerConf:
        # 用户消息队列大小
        UserMailboxSize: 102400
        # 系统消息队列大小
        SystemMailboxSize: 16
        # 工作线程数量
        WorkerNum: 1
      # 是否开启主从模式
      IsPrimarySecondaryMode: false



# 日志配置
SystemLogger:
  Path: ./example/data/logs
  # 日志文件名
  Name: "system-1"
  # 日志级别
  Level: debug
  # 是否打印调用文件信息
  Caller: true
  # 是否打印完整调用文件信息
  FullCaller: false
  # 是否显示日志颜色
  Color: true
  # 日志最大保存时间(默认15天)
  MaxAge: 720h
  # 日志切分周期(默认24h)
  RotationTime: 24h
  AsyncMode:
    # 开启异步模式(内部调试时可以关闭)
    Enable: true
    Config:
      # 刷新间隔
      FlushInterval: 1s
      # 缓冲区大小(满时会立即写入)
      BufferSize: 1048576  # 1MB

