services:
  mysql:
    image: mysql:8.0
    #command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    networks:
      ember_net:
        ipv4_address: 172.10.0.10

networks:
  ember_net:
    driver: bridge
    name: idlerpg_net
    ipam:
      config:
        - subnet: 172.10.0.0/16

