services:
  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - "172.26.28.98:6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      ember_net:
        ipv4_address: 172.10.0.15

networks:
  ember_net:
    external: true