## 系统基础配置

NodeConf:
  NodeId: 1
  # 系统状态(debug/release)
  SystemStatus: debug
  # 系统数据目录(持久化)
  PVCPath: ./example/data
  # 系统缓存目录
  PVPath: ./example/cache
  # 性能监控(0表示不开启监控)
  ProfilerInterval: 10s
  # 线程池大小
  AntsPoolSize: 10000

ClusterConf:
  ETCDConf:
    # etcd地址
    EndPoints:
      - ${REMOTE_HOST}:2379
    DialTimeout: 3s
    # etcd用户名
    UserName: root
    # etcd密码
    Password: 123456
    NoLogger: true
  RPCServers:
    # 监听地址
    - Addr: 0.0.0.0:6710
      # 协议
      Protoc: "tcp"
      # rpc类型
      Type: "rpcx"
    - Addr: 0.0.0.0:6711
      Protoc: "tcp"
      Type: "grpc"
    - Addr: nats://${REMOTE_HOST}:4222
      Protoc: "tcp"
      Type: "nats"
  DiscoveryType: etcd
  RemoteConfPath: ""
  # 服务发现监听路径
  DiscoveryConf:
    Path: /server/rpc
    MasterPath: /server/master

ServiceConf:
  OpenRemote: false
  RemoteConfPath: ""
  StartServices:
      # 服务id
    - ClassName: Service111
      ServiceId: 1
      # 服务名称
      ServiceName: Service111
      # 服务类型
      Type: test
      # 服务器ID
      ServerId: 2
      RpcType: "grpc"
      IsPrimarySecondaryMode: true
      WorkerConf:
        # 用户消息队列大小(默认128)
        UserMailboxSize: 128
        # 系统消息队列大小(默认16)
        SystemMailboxSize: 16
        # 工作线程数量(初始线程数,默认1)
        WorkerNum: 1
        # 最大工作线程数量(默认1)
        MaxWorkerNum: 10
        # 是否开启动态线程数调整(默认不开启)
        DynamicWorkerScaling: true
        # 虚拟线程比例(默认10)(当workerNum大于1时,虚拟线程倍率用来控制虚拟线程的数量 哈希环上的节点数量=workernum*rate)
        VirtualWorkerRate: 10
        # 线程池增长因子(默认1.5)(当负载大于最大负载时,则启动新的线程)
        GrowthFactor: 1.5
        # 线程池收缩因子(默认0.5)(当负载小于最小负载时,则收缩线程)
        ShrinkFactor: 0.5
        # 缩容冷却时间(默认1秒)(当负载小于最小负载时,则关闭多余的线程)
        ResizeCoolDown: 1s
        # 扩容策略名称(默认default,根据worker负载扩容)
        Strategy:
          # 策略名称
          Name: default
          Params:
            # 最大负载(默认10,超过就会启动动态扩容,扩容后超过半数无负载则开启缩容)
            max_load_threshold: 10
          Subs: # 子策略

# 日志配置
SystemLogger:
  Path: ./example/data/logs
  # 日志文件名
  Name: "system-slaver"
  # 日志级别
  Level: debug
  # 是否打印调用文件信息
  Caller: true
  # 是否打印完整调用文件信息
  FullCaller: false
  # 是否显示日志颜色
  Color: true
  # 日志最大保存时间(默认15天)
  MaxAge: 720h
  # 日志切分周期(默认24h)
  RotationTime: 24h
  AsyncMode:
    # 开启异步模式(内部调试时可以关闭)
    Enable: true
    Config:
      # 刷新间隔
      FlushInterval: 1s
      # 缓冲区大小(满时会立即写入)
      BufferSize: 1048576  # 1MB

